on: # Workflow for building and deploying a Jekyll site to GitHub Pages
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches: main # Runs on pushes targeting the main branch

permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
  cancel-in-progress: false # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/configure-pages@main
      - uses: actions/jekyll-build-pages@main
      - uses: actions/upload-pages-artifact@main
      - uses: actions/deploy-pages@main
